import torch

debug: True
image_path: "C:/Moein/AI/Datasets/Flicker-8k/Images"
captions_path: "C:/Moein/AI/Datasets/Flicker-8k"
batch_size: 8
num_workers: 0
lr: 1e-3
weight_decay: 1e-3
patience: 2
factor: 0.5
epochs: 5
device: torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_name: 'resnet50'
image_embedding: 2048
text_encoder_model: "distilbert-base-uncased"
text_embedding: 768
text_tokenizer: "distilbert-base-uncased"
max_length: 200

pretrained: False # for both image encoder and text encoder
trainable: False # for both image encoder and text encoder
temperature: 1.0

# image size
size: 224

# for projection head; used for both image and text encoders
num_projection_layers: 1
projection_dim: 256 
dropout: 0.1

# TEXT ENCODER CONFIG
text_model: 'bert-base-uncased'
text_len: 100
transformer_embed_dim: 768
freeze_text_encoder_weights: True

# AUDIO ENCODER CONFIG
audioenc_name: 'Cnn14'
out_emb: 2048
sampling_rate: 44100
duration: 5
fmin: 50
fmax: 14000
n_fft: 1028
hop_size: 320
mel_bins: 64
window_size: 1024

# PROJECTION SPACE CONFIG 
d_proj: 1024
temperature: 0.003

# TRAINING AND EVALUATION CONFIG
num_classes: 527
batch_size: 1024
demo: False